language: go
go:
  - 1.9
script:
  - go test -v ./...
before_deploy:
  - go get github.com/inconshreveable/mousetrap # temporary fix for travis build breaks for windows due to cobra dependency on mousetrap
  - GOOS=darwin GOARCH=amd64 go build -o b4a -v github.com/back4app/parse-cli
  - GOOS=windows GOARCH=386 go build -o b4a.exe -v github.com/back4app/parse-cli
  - GOOS=linux GOARCH=386 go build -o b4a_linux -v github.com/back4app/parse-cli
  - GOOS=linux GOARCH=arm go build -o b4a_linux_arm -v github.com/back4app/parse-cli
  - cp b4a parse
  - cp b4a.exe parse.exe
  - cp b4a_linux parse_linux
  - cp b4a_linux_arm parse_linux_arm
deploy:
  provider: releases
  api_key:
    secure: "y2pU0ZNr7Na8CX+p2Jou2wyg7Uzf/1/Ml38ue5PSSELEvWtjTwpbC4vJ/iP8PyEBCYr9NZ0Qti/M+a5mGFaocelRHu/A6f4GuujB3fKCadW1eRV9ncTqQpLtSJ7huOk7izMlz25rcvuEft5FSxnrckSECcW0qpzr6AQG67JB/9IEveR1XfXNCn0SDFydbBOTKxrnNIJksJtSj2v+pXNQZ0wBT++7+oSLgICks0qp61/4aVBYlC4YRvxqNq4681daD+ZrywHE03CTHLW9BiOAeT02RBNRY3crZ7mQ00+Khp69sF7A8NH1Pnn6p+50HQVXsT201uNCKFvqf4B3uxGEAs4qpcptgOfyh16q0wanD8A7vR7+tvjWFi0XMhPGFpxXTyZz9WygBB76o7S+PcoFJt9spYmEuxhWrirfVF4zNBj0iTZvyFhdRtCCcvLJAPhtaXaUjUd0DF+H7iLfia4Mwp0iejvLqzNKedfgoK9pDMfSgac7SRq6+Fm84Gp6ORpTna+kVHsY0UO3sZZ5j23dwo9bmnDIH/QJVdZdiShsERuwATMQH5biUzbTR6BWYR+yDV3yUuZiYRr//kda61eK1CDLwx2YybcDv2ikVKgMdt19TfpCF3IkUE1HncSJkegSxmgZaXAvqqeqvDyV7IksdCYQ64UjTBdpcycQUdFWEyU="

  file:
    - b4a
    - b4a.exe
    - b4a_linux
    - b4a_linux_arm
    - parse
    - parse.exe
    - parse_linux
    - parse_linux_arm
  skip_cleanup: true
  on:
    repo: back4app/parse-cli
    tags: true
    condition: $TRAVIS_TAG =~ ^release_.*
